#!/bin/bash

# GitHub Desktop Connection Helper for Existing Repository
echo "🚀 GitHub Desktop Connection Helper"
echo "===================================="
echo ""
echo "Since you already have the 'mins-mini-games' repository on GitHub:"
echo "Repository URL: https://github.com/hibikisori/mins-mini-games"
echo ""
echo "STEP 1: Clone Repository in GitHub Desktop"
echo "1. Open GitHub Desktop"
echo "2. Click 'Clone a repository from the Internet'"
echo "3. Select 'GitHub.com' tab"
echo "4. Find 'hibikisori/mins-mini-games' in your repositories"
echo "5. Choose local path: /Users/Hibikisori/Documents/python-projects/"
echo "6. Click 'Clone'"
echo ""
echo "STEP 2: Copy Your Game Files"
echo "After cloning, copy all your game files to the new repository folder:"
echo ""
echo "FROM: /Users/Hibikisori/Documents/python-projects/web-browser-games/"
echo "TO:   /Users/Hibikisori/Documents/python-projects/mins-mini-games/"
echo ""
echo "Run this command to copy all files:"
echo "cp -r /Users/Hibikisori/Documents/python-projects/web-browser-games/* /Users/Hibikisori/Documents/python-projects/mins-mini-games/"
echo ""
echo "STEP 3: Commit and Push in GitHub Desktop"
echo "1. GitHub Desktop will show all files as changes"
echo "2. Add commit message: 'Add complete web browser games collection'"
echo "3. Click 'Commit to main'"
echo "4. Click 'Push origin' to upload to GitHub"
echo ""
echo "STEP 4: Enable GitHub Pages (if not already enabled)"
echo "1. Go to https://github.com/hibikisori/mins-mini-games"
echo "2. Click Settings → Pages"
echo "3. Source: Deploy from a branch"
echo "4. Branch: main, Folder: / (root)"
echo "5. Click Save"
echo ""
echo "🎮 Your games will be live at:"
echo "https://hibikisori.github.io/mins-mini-games/"
echo ""
echo "Game URLs:"
echo "- PathGuard: https://hibikisori.github.io/mins-mini-games/games/defend-line/"
echo "- Memory Link: https://hibikisori.github.io/mins-mini-games/games/memory-link/"
echo "- Reaction Time: https://hibikisori.github.io/mins-mini-games/games/reaction-time/"
