#!/bin/bash

# GitHub Desktop Setup Helper for hibikisori/mins-mini-games
echo "🚀 GitHub Desktop Setup Helper"
echo "==============================="
echo "Repository: hibikisori/mins-mini-games"
echo ""
echo "STEP 1: Clone Your Existing Repository"
echo "1. Open GitHub Desktop"
echo "2. Click 'Clone a repository from the Internet'"
echo "3. Choose 'GitHub.com' tab"
echo "4. Find 'hibikisori/mins-mini-games' in your repositories list"
echo "5. Set Local path: /Users/Hibikisori/Documents/python-projects/"
echo "6. Click 'Clone'"
echo ""
echo "STEP 2: Copy Your Game Files"
echo "After cloning, copy all your game files to the cloned repository:"
echo ""
echo "cp -r /Users/Hibikisori/Documents/python-projects/web-browser-games/* /Users/Hibikisori/Documents/python-projects/mins-mini-games/"
echo ""
echo "Or manually copy all files from:"
echo "FROM: /Users/Hibikisori/Documents/python-projects/web-browser-games/"
echo "TO:   /Users/Hibikisori/Documents/python-projects/mins-mini-games/"
echo ""
echo "STEP 3: Commit and Push in GitHub Desktop"
echo "1. GitHub Desktop will show all your files as changes"
echo "2. Add a commit message: 'Add Min's Mini Games collection - PathGuard, Memory Link, Reaction Time'"
echo "3. Click 'Commit to main'"
echo "4. Click 'Push origin' to upload to GitHub"
echo ""
echo "STEP 4: Enable GitHub Pages"
echo "1. Go to https://github.com/hibikisori/mins-mini-games"
echo "2. Click Settings → Pages"
echo "3. Source: Deploy from a branch"
echo "4. Branch: main, Folder: / (root)"
echo "5. Click Save"
echo ""
echo "🎮 Your games will be live at:"
echo "https://hibikisori.github.io/mins-mini-games/"
echo ""
echo "Individual game URLs:"
echo "- PathGuard: https://hibikisori.github.io/mins-mini-games/games/defend-line/"
echo "- Memory Link: https://hibikisori.github.io/mins-mini-games/games/memory-link/"
echo "- Reaction Time: https://hibikisori.github.io/mins-mini-games/games/reaction-time/"
