#!/bin/bash

# GitHub Desktop Setup Helper
echo "🚀 GitHub Desktop Setup Helper"
echo "==============================="
echo ""
echo "STEP 1: Create Repository in GitHub Desktop"
echo "1. Open GitHub Desktop"
echo "2. Click 'Create a New Repository on your hard drive'"
echo "3. Use these settings:"
echo "   - Name: web-browser-games"
echo "   - Local path: /Users/Hibikisori/Documents/python-projects/"
echo "   - ✅ Initialize with README"
echo "   - Git ignore: Node"
echo "   - License: MIT License (optional)"
echo "4. Click 'Create Repository'"
echo ""
echo "STEP 2: Copy Files"
echo "After creating the repository, run this command:"
echo ""
echo "cp -r /Users/Hibikisori/Documents/python-projects/web-browser-games/* /Users/Hibikisori/Documents/python-projects/web-browser-games-new/"
echo ""
echo "Or manually copy all files from:"
echo "FROM: /Users/Hibikisori/Documents/python-projects/web-browser-games/"
echo "TO:   /Users/Hibikisori/Documents/python-projects/web-browser-games/ (the new one GitHub Desktop created)"
echo ""
echo "STEP 3: Commit and Push in GitHub Desktop"
echo "1. GitHub Desktop will show all your files as changes"
echo "2. Add a commit message: 'Add web browser games collection'"
echo "3. Click 'Commit to main'"
echo "4. Click 'Publish repository' to push to GitHub"
echo ""
echo "STEP 4: Enable GitHub Pages"
echo "1. Go to your repository on GitHub.com"
echo "2. Click Settings → Pages"
echo "3. Source: Deploy from a branch"
echo "4. Branch: main, Folder: / (root)"
echo "5. Click Save"
echo ""
echo "Your games will be live at:"
echo "https://YOUR_USERNAME.github.io/web-browser-games/"
