#!/bin/bash

# VS Code GitHub Extension Setup
echo "📝 VS Code GitHub Extension Setup"
echo "==================================="
echo ""
echo "STEP 1: Install Extensions"
echo "1. Open VS Code"
echo "2. Install these extensions:"
echo "   - GitHub Pull Requests and Issues"
echo "   - GitLens"
echo "   - GitHub Repositories"
echo ""
echo "STEP 2: Open Your Project"
echo "1. File → Open Folder"
echo "2. Select: /Users/Hibikisori/Documents/python-projects/web-browser-games"
echo ""
echo "STEP 3: Initialize Git (if not done)"
echo "1. Open Terminal in VS Code (Ctrl+backtick)"
echo "2. Run: git init"
echo "3. Run: git add ."
echo "4. Run: git commit -m \"Initial commit\""
echo ""
echo "STEP 4: Create GitHub Repository"
echo "1. Press Cmd+Shift+P"
echo "2. Type 'GitHub: Create Repository'"
echo "3. Choose 'Create new repository on GitHub'"
echo "4. Name: web-browser-games"
echo "5. Make it Public"
echo "6. Click Create"
echo ""
echo "STEP 5: Enable GitHub Pages"
echo "1. Go to GitHub.com → Your repository"
echo "2. Settings → Pages"
echo "3. Source: Deploy from a branch"
echo "4. Branch: main, Folder: / (root)"
echo "5. Save"
echo ""
echo "Your site will be available at:"
echo "https://YOUR_USERNAME.github.io/web-browser-games/"
